networks:
  filmony-network:
    driver: bridge

volumes:
  filmony-pgdata:
  filmony-rustfs-data:
  filmony-redis-data:

x-on-filmony-network: &on-filmony-network
  restart: unless-stopped
  networks:
    - filmony-network

x-app-service: &app-service
  <<: *on-filmony-network
  build:
    context: backend
    dockerfile: Dockerfile
    target: dev
  env_file:
    - vars/.env.development
  working_dir: /opt/app
  volumes:
    - ./backend/src:/opt/app/src
    - ./backend/pyproject.toml:/opt/app/pyproject.toml
    - ./backend/uv.lock:/opt/app/uv.lock
    - ./backend/alembic.ini:/opt/app/alembic.ini

x-app-with-deps: &app-with-deps
  <<: *app-service
  depends_on:
    - filmony-postgres
    - filmony-rustfs
    - filmony-redis

services:
  filmony-postgres:
    <<: *on-filmony-network
    image: postgres:18-alpine
    container_name: filmony-postgres
    environment:
      POSTGRES_USER: filmony
      POSTGRES_PASSWORD: filmony
      POSTGRES_DB: filmony
    ports:
      - "55432:5432"
    volumes:
      - filmony-pgdata:/var/lib/postgresql/data

  filmony-redis:
    <<: *on-filmony-network
    image: redis:8-alpine
    container_name: filmony-redis
    ports:
      - '56379:6379'
    volumes:
      - filmony-redis-data:/data

  filmony-rustfs:
    <<: *on-filmony-network
    image: rustfs/rustfs:latest
    container_name: filmony-rustfs
    ports:
      - '7900:9000'
      - '7901:9001'
    volumes:
      - filmony-rustfs-data:/data
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: 'true'
    command: ['/data']

  filmony-backend:
    <<: *app-with-deps
    container_name: filmony-backend
    command: python src/main.py
    ports:
      - "6749:8000"
    environment:
      RUSTFS_INTERNAL_BASE_URL: http://filmony-rustfs:9000

  filmony-celery-worker:
    <<: *app-with-deps
    container_name: filmony-celery-worker
    command: celery -A celery_app worker --loglevel=INFO
