networks:
  filmony:
    name: filmony-network
    driver: bridge
  homelab-infra:
    name: homelab-infra-network
    external: true

x-backend: &backend
  restart: unless-stopped
  networks:
    - filmony
  build:
    context: backend
    dockerfile: Dockerfile
    target: prod
  env_file:
    - vars/.env.production
  working_dir: /opt/app

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - filmony
    command: ['redis-server', '--appendonly', 'yes']

  backend:
    <<: *backend
    container_name: filmony-backend
    networks:
      - filmony
      - homelab-infra
    command: python src/main.py
    ports:
      - '8100:8000'
    depends_on:
      - redis

  celery-worker:
    <<: *backend
    command: celery -A celery_app worker --loglevel=INFO
    depends_on:
      - redis
