networks:
  filmony:
    name: filmony-network
    driver: bridge
  homelab-infra:
    name: homelab-infra-network
    external: true

x-backend: &backend
  restart: unless-stopped
  image: ghcr.io/${GITHUB_REPO}/backend:latest
  env_file:
    - vars/.env.production
  working_dir: /opt/app
  networks:
    - filmony
    - homelab-infra

services:
  backend:
    <<: *backend
    container_name: filmony-backend
    command: python src/main.py
    networks:
      filmony: {}
      homelab-infra:
        aliases:
          - filmony-backend

  celery-worker:
    <<: *backend
    container_name: filmony-celery-worker
    command: celery -A celery_app worker --loglevel=INFO
    depends_on:
      - backend
