networks:
  filmony:
    name: filmony-network
    driver: bridge
  homelab-infra:
    name: homelab-infra-network
    external: true

volumes:
  rustfs-data:

x-app: &app
  restart: unless-stopped
  build:
    context: backend
    dockerfile: Dockerfile
    target: dev
  env_file:
    - vars/.env.development
    - vars/.env.development.local
  working_dir: /opt/app
  volumes:
    - ./backend/src:/opt/app/src
    - ./backend/pyproject.toml:/opt/app/pyproject.toml
    - ./backend/uv.lock:/opt/app/uv.lock
    - ./backend/alembic.ini:/opt/app/alembic.ini

services:
  rustfs:
    restart: unless-stopped
    networks:
      - filmony
    image: rustfs/rustfs:1.0.0-beta.1
    ports:
      - '7900:9000'
      - '7901:9001'
    volumes:
      - rustfs-data:/data
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: 'true'
    command: ['/data']

  backend:
    <<: *app
    container_name: filmony-backend
    networks:
      filmony: {}
      homelab-infra:
        aliases:
          - filmony-backend
    depends_on:
      - rustfs
    command: python src/main.py
    ports:
      - '8888:8000'

  celery-worker:
    <<: *app
    networks:
      - filmony
      - homelab-infra
    depends_on:
      - rustfs
    command: celery -A celery_app worker --loglevel=INFO
