"""edit-len-comm

Revision ID: 33622715f72c
Revises: 9ff94784da45
Create Date: 2026-05-06 20:34:23.037520

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '33622715f72c'
down_revision: str | Sequence[str] | None = '9ff94784da45'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'movie_card_comment',
        'text',
        existing_type=sa.VARCHAR(length=250),
        type_=sa.String(length=100),
        existing_nullable=False,
        # Existing rows can exceed 100 chars; truncate during type change.
        postgresql_using='left(text, 100)',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'movie_card_comment',
        'text',
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=250),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
