"""init

Revision ID: 8a555730c078
Revises:
Create Date: 2026-05-06 01:26:36.424054

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8a555730c078'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'film',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('kinopoisk_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('poster_url', sa.String(length=2048), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_film_kinopoisk_id'), 'film', ['kinopoisk_id'], unique=True)
    op.create_table(
        'user',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=255), nullable=True),
        sa.Column('first_name', sa.String(length=255), nullable=True),
        sa.Column('last_name', sa.String(length=255), nullable=True),
        sa.Column('photo_url', sa.String(length=2048), nullable=True),
        sa.Column('profile_slug', sa.String(length=32), nullable=False),
        sa.Column('display_name', sa.String(length=120), nullable=True),
        sa.Column('bio', sa.String(length=500), nullable=True),
        sa.Column('language_code', sa.String(length=32), nullable=True),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_profile_slug'), 'user', ['profile_slug'], unique=True)
    op.create_index(op.f('ix_user_telegram_user_id'), 'user', ['telegram_user_id'], unique=True)
    op.create_table(
        'movie_card',
        sa.Column('user_id', sa.Uuid(), nullable=False),
        sa.Column('film_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Float(), nullable=False),
        sa.Column('company', sa.String(length=32), nullable=False),
        sa.Column('mood_before', sa.String(length=32), nullable=False),
        sa.Column('mood_after', sa.String(length=32), nullable=False),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['film_id'], ['film.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'film_id', name='uq_movie_card_user_film'),
    )
    op.create_index(op.f('ix_movie_card_film_id'), 'movie_card', ['film_id'], unique=False)
    op.create_index(op.f('ix_movie_card_user_id'), 'movie_card', ['user_id'], unique=False)
    op.create_table(
        'user_subscription',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('follower_user_id', sa.Uuid(), nullable=False),
        sa.Column('following_user_id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('follower_user_id <> following_user_id', name='ck_no_self_subscription'),
        sa.ForeignKeyConstraint(['follower_user_id'], ['user.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['following_user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'follower_user_id', 'following_user_id', name='uq_user_subscription_pair'
        ),
    )
    op.create_index(
        op.f('ix_user_subscription_follower_user_id'),
        'user_subscription',
        ['follower_user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_user_subscription_following_user_id'),
        'user_subscription',
        ['following_user_id'],
        unique=False,
    )
    op.create_table(
        'movie_card_tag',
        sa.Column('movie_card_id', sa.Integer(), nullable=False),
        sa.Column('tag', sa.String(length=40), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['movie_card_id'], ['movie_card.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('movie_card_id', 'tag', name='uq_movie_card_tag_unique'),
    )
    op.create_index(
        op.f('ix_movie_card_tag_movie_card_id'), 'movie_card_tag', ['movie_card_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_card_tag_movie_card_id'), table_name='movie_card_tag')
    op.drop_table('movie_card_tag')
    op.drop_index(op.f('ix_user_subscription_following_user_id'), table_name='user_subscription')
    op.drop_index(op.f('ix_user_subscription_follower_user_id'), table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_index(op.f('ix_movie_card_user_id'), table_name='movie_card')
    op.drop_index(op.f('ix_movie_card_film_id'), table_name='movie_card')
    op.drop_table('movie_card')
    op.drop_index(op.f('ix_user_telegram_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_profile_slug'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_film_kinopoisk_id'), table_name='film')
    op.drop_table('film')
    # ### end Alembic commands ###
