"""comms

Revision ID: 9ff94784da45
Revises: 8a555730c078
Create Date: 2026-05-06 02:12:57.340978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff94784da45'
down_revision: Union[str, Sequence[str], None] = '8a555730c078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_card_comment',
    sa.Column('movie_card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_card_id'], ['movie_card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['movie_card_comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movie_card_comment_card_parent_id', 'movie_card_comment', ['movie_card_id', 'parent_comment_id', 'id'], unique=False)
    op.create_index(op.f('ix_movie_card_comment_movie_card_id'), 'movie_card_comment', ['movie_card_id'], unique=False)
    op.create_index(op.f('ix_movie_card_comment_parent_comment_id'), 'movie_card_comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_movie_card_comment_user_id'), 'movie_card_comment', ['user_id'], unique=False)
    op.add_column('film', sa.Column('genres', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('film', 'genres')
    op.drop_index(op.f('ix_movie_card_comment_user_id'), table_name='movie_card_comment')
    op.drop_index(op.f('ix_movie_card_comment_parent_comment_id'), table_name='movie_card_comment')
    op.drop_index(op.f('ix_movie_card_comment_movie_card_id'), table_name='movie_card_comment')
    op.drop_index('ix_movie_card_comment_card_parent_id', table_name='movie_card_comment')
    op.drop_table('movie_card_comment')
    # ### end Alembic commands ###
