"""card

Revision ID: bd8f039d04fe
Revises: r0s1t2u3v456
Create Date: 2026-05-14 01:01:18.799826

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd8f039d04fe'
down_revision: str | Sequence[str] | None = 'r0s1t2u3v456'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'catalog_item',
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    )
    op.drop_index(op.f('ix_feed_post_user_id_created_at_id'), table_name='feed_post')
    op.create_index(
        'ix_feed_post_user_id_created_at_id',
        'feed_post',
        ['user_id', 'created_at', 'id'],
        unique=False,
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.drop_index(op.f('ix_movie_card_created_at_id'), table_name='movie_card')
    op.create_index(
        'ix_movie_card_created_at_id',
        'movie_card',
        ['created_at', 'id'],
        unique=False,
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.drop_index(
        op.f('ix_movie_card_user_favorites_order'),
        table_name='movie_card',
        postgresql_where='(is_favorite IS TRUE)',
    )
    op.create_index(
        'ix_movie_card_user_favorites_order',
        'movie_card',
        ['user_id', 'favorite_marked_at', 'id'],
        unique=False,
        postgresql_ops={'favorite_marked_at': 'DESC NULLS LAST', 'id': 'DESC'},
        postgresql_where=sa.text('is_favorite IS TRUE'),
    )
    op.drop_index(op.f('ix_movie_card_user_id_created_at_id'), table_name='movie_card')
    op.create_index(
        'ix_movie_card_user_id_created_at_id',
        'movie_card',
        ['user_id', 'created_at', 'id'],
        unique=False,
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.alter_column(
        'user_card_category',
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index(op.f('ix_user_reaction_target_kind_type_id'), table_name='user_reaction')
    op.create_index(
        'ix_user_reaction_target_kind_type_id',
        'user_reaction',
        ['target_kind', 'target_id', 'reaction_type_id', 'id'],
        unique=False,
        postgresql_ops={'id': 'DESC'},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_user_reaction_target_kind_type_id',
        table_name='user_reaction',
        postgresql_ops={'id': 'DESC'},
    )
    op.create_index(
        op.f('ix_user_reaction_target_kind_type_id'),
        'user_reaction',
        ['target_kind', 'target_id', 'reaction_type_id', sa.literal_column('id DESC')],
        unique=False,
    )
    op.alter_column(
        'user_card_category',
        'created_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index(
        'ix_movie_card_user_id_created_at_id',
        table_name='movie_card',
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.create_index(
        op.f('ix_movie_card_user_id_created_at_id'),
        'movie_card',
        ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')],
        unique=False,
    )
    op.drop_index(
        'ix_movie_card_user_favorites_order',
        table_name='movie_card',
        postgresql_ops={'favorite_marked_at': 'DESC NULLS LAST', 'id': 'DESC'},
        postgresql_where=sa.text('is_favorite IS TRUE'),
    )
    op.create_index(
        op.f('ix_movie_card_user_favorites_order'),
        'movie_card',
        [
            'user_id',
            sa.literal_column('favorite_marked_at DESC NULLS LAST'),
            sa.literal_column('id DESC'),
        ],
        unique=False,
        postgresql_where='(is_favorite IS TRUE)',
    )
    op.drop_index(
        'ix_movie_card_created_at_id',
        table_name='movie_card',
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.create_index(
        op.f('ix_movie_card_created_at_id'),
        'movie_card',
        [sa.literal_column('created_at DESC'), sa.literal_column('id DESC')],
        unique=False,
    )
    op.drop_index(
        'ix_feed_post_user_id_created_at_id',
        table_name='feed_post',
        postgresql_ops={'created_at': 'DESC', 'id': 'DESC'},
    )
    op.create_index(
        op.f('ix_feed_post_user_id_created_at_id'),
        'feed_post',
        ['user_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')],
        unique=False,
    )
    op.drop_column('catalog_item', 'created_at')
    # ### end Alembic commands ###
